### ISSUE TITLE
MiSTerManual license?

### ISSUE THREAD

**Issue by cognitivegears** [adreeve/MiSTerManual#3]
If possible, can you please clarify the MiSTerManual license? Is this under one of the Creative Commons licenses etc?

**Comment by adreeve** [comment]
What are you wanting to do with it?
   
  
    
   
  
   This was created with the intent of documenting the various systems for me and I just wanted to share that info. I have not thought about licenses given that this isn't open source software... it's just documentation / instructions that has been gathered from other sources and experimentation.
   
  
    
   
  
   - Thanks, Alan
   
   
   
    On 09/08/2022 7:18 AM CDT Nathan Byrd ***@***.***> wrote:
    
   
     
    
   
     
    
     
   If possible, can you please clarify the MiSTerManual license? Is this under one of the Creative Commons licenses etc?

**Comment by cognitivegears** [comment]
I've been playing around with making a UI for MiSTer using a web browser to select games. The idea is to use python on the server to run a simple web server that would launch titles via MRA and MGL files (similar to SAM.) The interface would be all client-side due to performance limitations of Linux on MiSTer.

In any case, some of the content in here I think could be useful for the web interface, particularly the pictures of the systems, descriptions etc. Just wanted to see if this might be in a license that would mean I could use it for that project as well.

**Comment by adreeve** [comment]
I try to honor the various licenses as I see them for images I use. Many of them come from Wikipedia I think. But I can't definitively say I'm perfect on that so I wouldn't base your usage of any images here off of my usage of such.
   
  
    
   
  
   - Thanks, Alan
   
   
   
    On 09/09/2022 12:26 AM CDT Nathan Byrd ***@***.***> wrote:
    
   
     
    
   
     
    
     
   I've been playing around with making a UI for MiSTer using a web browser to select games. The idea is to use python on the server to run a simple web server that would launch titles via MRA and MGL files (similar to SAM.) The interface would be all client-side due to performance limitations of Linux on MiSTer. 
   In any case, some of the content in here I think could be useful for the web interface, particularly the pictures of the systems, descriptions etc. Just wanted to see if this might be in a license that would mean I could use it for that project as well.
